# Generated by Django 5.1.2 on 2024-11-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_stripe_product_id_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='currency',
            field=models.CharField(default='inr', max_length=3),
        ),
    ]
