# Generated by Django 5.1.2 on 2024-11-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_remove_order_order_status_orderitem_shipping_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Success', 'Success'), ('Refund Demanded', 'Refund Demanded'), ('Refund Processed', 'Refund Processed')], max_length=20),
        ),
    ]
