# Generated by Django 5.1.2 on 2024-11-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='payment_status',
            field=models.CharField(choices=[('Success', 'Success'), ('Refund Demanded', 'Refund Demanded'), ('Refund Processed', 'Refund Processed')], default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Success', 'Success'), ('Refund Demanded', 'Refund Demanded'), ('Refund Processed', 'Refund Processed'), ('Partially Refunded', 'Partially Refunded')], max_length=20),
        ),
    ]
