# Generated by Django 5.1.2 on 2024-11-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_orderitem_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='payment_status',
            field=models.CharField(choices=[('Success', 'Success'), ('Refund Demanded', 'Refund Demanded'), ('Refund Processed', 'Refund Processed')], max_length=20),
        ),
    ]
