# Generated by Django 5.1.2 on 2024-11-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_cart_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
